[package]
name = "web-scrapper-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.14"
tokio = { version = "1", features = ["full"] }
